import type { Order } from "../services/order-service.js";
import type { SendEmailInput } from "../services/email-service.js";
import { emailButton, escapeHtml, formatAmount, label, palette, paragraph, productSections, renderEditorialEmail, sans, section, serif, siteUrl, table, type EmailProduct } from "./editorial.js";

export type EmailContext = { webOrigin: string; images?: Map<string, string> };
function orderTotals(order: Order, paid: boolean) {
  const amount = (value: number) => formatAmount(value, order.currency);
  const rows = [ ["Subtotal", amount(order.subtotal)], ...(order.discount > 0 ? [[`Promo${order.promoCode ? ` (${order.promoCode})` : ""}`, `−${amount(order.discount)}`]] : []), ["Shipping", order.shipping === 0 ? "Complimentary" : amount(order.shipping)], ...(!order.taxIncluded ? [[`VAT (${Number((order.taxRate * 100).toFixed(2))}%)`, amount(order.tax)]] : []) ];
  return table(rows.map(([name, value]) => `<tr><td style="padding:8px 12px 8px 0;font:13px/1.6 ${sans};color:${palette.muted};overflow-wrap:anywhere;">${escapeHtml(name)}</td><td align="right" style="padding:8px 0;font:13px/1.6 ${sans};color:${palette.ink};white-space:nowrap;">${value}</td></tr>`).join("") + `<tr><td style="padding:18px 0 4px;border-top:1px solid ${palette.line};font:bold 16px/1.5 ${sans};color:${palette.ink};">${paid ? "Total paid" : "Order total"}</td><td align="right" style="padding:18px 0 4px;border-top:1px solid ${palette.line};font:28px/1.4 ${serif};color:${palette.ink};white-space:nowrap;">${amount(order.total)}</td></tr>${order.taxIncluded ? `<tr><td colspan="2" align="right" style="font:11px/1.8 ${sans};color:${palette.muted};">Includes ${amount(order.tax)} VAT (${Number((order.taxRate * 100).toFixed(2))}%)</td></tr>` : ""}`);
}
function addressLines(order: Order) {
  const a = order.shippingAddress;
  return [order.customer.name, a.line1, a.line2, [a.city, a.region, a.postalCode].filter(Boolean).join(", "), a.country].filter(Boolean) as string[];
}
function orderDetails(order: Order, paid: boolean) {
  return section(`${label("Order details")}<p style="margin:10px 0 18px;font:12px/1.8 ${sans};color:${palette.muted};word-break:break-all;">${escapeHtml(order.id)}</p>${orderTotals(order, paid)}`, palette.paper) + section(table(`<tr><td class="email-stack" width="50%" valign="top" style="padding-right:20px;">${label("Delivering to")}<p style="margin:10px 0 0;font:13px/1.8 ${sans};color:${palette.ink};">${addressLines(order).map(escapeHtml).join("<br/>")}</p></td><td class="email-stack" width="50%" valign="top">${label("What happens next")}${paragraph(paid ? "We will email you when fulfillment updates are available." : "Once payment is confirmed, we will email your order confirmation.")}</td></tr>`));
}
export function buildCustomerOrderEmail(order: Order, paid: boolean, context: EmailContext): SendEmailInput {
  const subject = paid ? `Your Sekanae order ${order.id} is confirmed` : `Payment pending for your Sekanae order ${order.id}`;
  const items = order.items.map(item => ({ ...item, image: context.images?.get(item.productId) }));
  const rows = productSections(items, order.currency, context.webOrigin) + orderDetails(order, paid) + section(emailButton(paid ? "Visit the boutique" : "Contact client care", siteUrl(context.webOrigin, paid ? "/shop" : "/client-care")));
  const total = formatAmount(order.total, order.currency);
  return { orderId: order.id, to: order.customer.email, subject, template: paid ? "customer_payment_confirmed" : "customer_order_received", html: renderEditorialEmail({ title: paid ? "A beautiful" : "Your selection,", accent: paid ? "choice." : "one step away.", eyebrow: paid ? "Order confirmed" : "Payment pending", intro: paid ? `Thank you, ${order.customer.name}. Your payment is confirmed.` : `Thank you, ${order.customer.name}. We received your order. Payment is still pending.`, preheader: `Order ${order.id}. ${paid ? "Total paid" : "Order total"}: ${total}.`, webOrigin: context.webOrigin, rows, footerNote: paid ? "This is a service email confirming your purchase." : "This is a service email about your pending order." }), text: [paid ? "Your payment is confirmed." : "We received your order. Payment is still pending.", `Order: ${order.id}`, ...order.items.map(item => `${item.name} / ${item.color} × ${item.quantity}: ${formatAmount(item.lineTotal, order.currency)}`), `Subtotal: ${formatAmount(order.subtotal, order.currency)}`, ...(order.discount > 0 ? [`Promo${order.promoCode ? ` (${order.promoCode})` : ""}: −${formatAmount(order.discount, order.currency)}`] : []), `Shipping: ${formatAmount(order.shipping, order.currency)}`, `VAT${order.taxIncluded ? " included" : ""}: ${formatAmount(order.tax, order.currency)}`, `${paid ? "Total paid" : "Order total"}: ${total}`, "Delivering to:", ...addressLines(order), `Client care: ${siteUrl(context.webOrigin, "/client-care")}`].join("\n") };
}
export function buildAdminOrderEmail(order: Order, paid: boolean, email: string, context: EmailContext): SendEmailInput {
  return { orderId: order.id, to: email, subject: `${paid ? "Paid" : "New"} Sekanae order ${order.id}`, template: paid ? "admin_order_paid" : "admin_order_created", html: renderEditorialEmail({ title: paid ? "Payment" : "New order", accent: paid ? "confirmed." : "received.", eyebrow: "SEKANAE / Studio operations", preheader: `${order.customer.name} · ${formatAmount(order.total, order.currency)}`, webOrigin: context.webOrigin, rows: section(`${label("Customer")}${paragraph(`${order.customer.name} (${order.customer.email})`)}${label("Order status")}${paragraph(`${order.status} / ${order.paymentStatus}`)}`) + orderDetails(order, paid) + section(table(order.items.map(item => `<tr><td style="padding:12px 12px 12px 0;border-bottom:1px solid ${palette.line};">${escapeHtml(item.name)}<br/><span style="font-size:12px;">${escapeHtml(item.color)} · Qty ${item.quantity}</span></td><td align="right" style="white-space:nowrap;border-bottom:1px solid ${palette.line};">${formatAmount(item.lineTotal, order.currency)}</td></tr>`).join(""))) + section(emailButton("Open orders", siteUrl(context.webOrigin, "/admin/orders"))), footerNote: "An operational notification for the SEKANAE studio." }), text: `${paid ? "Paid" : "New"} order ${order.id} from ${order.customer.name} (${order.customer.email}). Total: ${formatAmount(order.total, order.currency)}. Status: ${order.status} / ${order.paymentStatus}.` };
}
export function buildLoginCodeEmail(input: { email: string; code: string; purpose: "create" | "sign-in"; ttlSeconds: number; webOrigin: string }): SendEmailInput {
  const create = input.purpose === "create";
  const subject = create ? "Verify your SEKANAE account" : "Your SEKANAE sign-in code";
  const minutes = input.ttlSeconds / 60;
  const expiry = Number.isInteger(minutes) ? `${minutes} minute${minutes === 1 ? "" : "s"}` : `${input.ttlSeconds} seconds`;
  return { to: input.email, subject, template: create ? "customer_account_code" : "customer_sign_in_code", html: renderEditorialEmail({ title: create ? "Welcome to" : "Welcome", accent: create ? "SEKANAE." : "back.", eyebrow: create ? "Verify your account" : "Your sign-in code", intro: create ? "One small step to finish creating your account." : "Your one-time code is ready.", preheader: `Your verification code expires in ${expiry}.`, webOrigin: input.webOrigin, rows: section(`${label("Your verification code")}<p class="email-code" style="margin:18px 0;font:bold 38px/1.5 ${sans};letter-spacing:8px;color:${palette.ink};">${escapeHtml(input.code)}</p>${paragraph(`Use this code to ${create ? "finish creating" : "sign in to"} your SEKANAE account. It expires in ${expiry}.`)}`, palette.paper) + section(paragraph("If you did not request this code, you can ignore this email. Keep this code private.")), footerNote: "A service email to help you access your SEKANAE account." }), text: `Your SEKANAE verification code is ${input.code}. It expires in ${expiry}. If you did not request this code, you can ignore this email.` };
}
export function buildNewsletterEmail(input: { email: string; subject: string; previewText?: string; html: string; unsubscribeUrl: string; webOrigin: string; welcome?: boolean }) {
  return renderEditorialEmail({ title: input.welcome ? "Welcome to" : input.subject, accent: input.welcome ? "our world." : undefined, eyebrow: input.welcome ? "SEKANAE / Welcome note" : "SEKANAE / From the studio", intro: input.welcome ? "Considered arrivals, thoughtful edits, and notes from the studio." : undefined, preheader: input.previewText ?? input.subject, webOrigin: input.webOrigin, rows: section(`<div class="email-content" style="font:16px/1.8 ${sans};color:${palette.muted};">${input.html}</div>`), footerNote: `You are receiving this because ${input.email} opted in to SEKANAE updates.`, unsubscribe: { url: input.unsubscribeUrl, label: "Unsubscribe from studio updates" } });
}
export function buildCartReminderEmail(input: { email: string; final: boolean; items: EmailProduct[]; currency: string; unsubscribeUrl: string; webOrigin: string }): SendEmailInput {
  const lead = input.final ? "One last note about the pieces in your saved cart. Return whenever the moment feels right." : "The pieces you selected are saved in your cart. Return whenever the moment feels right.";
  const subject = input.final ? "A final note about your SEKANAE cart" : "Your SEKANAE edit is waiting";
  const url = siteUrl(input.webOrigin, "/cart");
  return { to: input.email, subject, template: input.final ? "abandoned_cart_final" : "abandoned_cart_first", html: renderEditorialEmail({ title: input.final ? "One last" : "Still on", accent: input.final ? "studio note." : "your mind?", eyebrow: "Your saved SEKANAE edit", intro: lead, preheader: lead, webOrigin: input.webOrigin, rows: productSections(input.items, input.currency, input.webOrigin) + section(`${paragraph("Prices and availability are confirmed at checkout. Shipping, taxes, and any eligible promo discounts are calculated there.")}${emailButton("Return to your cart", url)}`, palette.paper), footerNote: "Our studio sends at most two reminders about your saved cart.", unsubscribe: { url: input.unsubscribeUrl, label: "Stop cart reminders" } }), text: [lead, ...input.items.map(item => `${item.name} / ${item.color} × ${item.quantity}: ${formatAmount(item.lineTotal, input.currency)}`), "Prices, availability, delivery and taxes are confirmed at checkout.", `Return to your cart: ${url}`, `Stop cart reminders: ${input.unsubscribeUrl}`].join("\n") };
}
